# Generated by Django 4.1.4 on 2022-12-08 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classlist', '0003_alter_meetings_end_time_alter_meetings_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetings',
            name='end_time',
            field=models.CharField(default='00.00.00.000000-05:00', max_length=100),
        ),
        migrations.AlterField(
            model_name='meetings',
            name='start_time',
            field=models.CharField(default='00.00.00.000000-05:00', max_length=100),
        ),
    ]
